#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "${BACKEND_USER}" WITH LOGIN PASSWORD '${BACKEND_PASSWORD}';
	CREATE DATABASE "${BACKEND_DB}";
	GRANT ALL PRIVILEGES ON DATABASE "${BACKEND_DB}" TO "${BACKEND_USER}";
EOSQL