#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "${BACKEND_USER}" WITH LOGIN PASSWORD '${BACKEND_PASSWORD}' SUPERUSER;
	CREATE DATABASE "${BACKEND_DB}";
	GRANT ALL PRIVILEGES ON DATABASE "${BACKEND_DB}" TO "${BACKEND_USER}";
	GRANT ALL PRIVILEGES ON SCHEMA public TO "${BACKEND_USER}";

	CREATE DATABASE "dev_db";
  GRANT ALL PRIVILEGES ON DATABASE "dev_db" TO "${BACKEND_USER}";
  GRANT ALL PRIVILEGES ON SCHEMA public TO "${BACKEND_USER}";
EOSQL